### ISSUE TITLE
not support no std?

### ISSUE THREAD

**Issue by muei** [cat-in-136/ws2812-esp32-rmt-driver#50]
error[E0405]: cannot find trait `Sync` in this scope
  --> /home/esp/.cargo/registry/src/index.crates.io-6f17d22bba150
01f/thiserror-1.0.61/src/aserror.rs:50:40
   |
50 | ...ror + Send + Sync + UnwindSafe + 'a {}
   |                 ^^^^ not found in this scope
   |
help: consider importing this trait
   |
1  + use core::marker::Sync;

**Comment by cat-in-136** [comment]
It is obvious from the source that it is not supported.

It is a candidate for the work item but I have not worked on.

**Comment by spectrachrome** [comment]
Hi! 😊 @cat-in-136 

I'd need this feature for a project and would be open to help with `no_std` support in a PR.
Have you had a look already to know what needs to be done to get this working without the standard library? If yes, please let me know.

Kind greetings,
Mo

**Comment by cat-in-136** [comment]
As I mentioned in June, I haven't started work yet, so I haven't done any research on this crate-specific topic.

This is a common no_std story that you all know, where the no_std support tasks can be divided into two phases: the case with alloc and the case without alloc.

In the case with alloc, it would be a simple matter to remove the parts depending on the std library, and the logic would not need to be changed. But the same work would be required for the dependent crates. For example, since thiserror crate does not support no_std, it would be necessary to switch to a no_std-compatible library such as snafu.
In the case without alloc, in addition, it is necessary to introduce new APIs for using only pre-allocated memory, and disabling existing APIs for dynamic memory allocation without alloc.

**Comment by spectrachrome** [comment]
A story (almost) all of us know. That is already quite helpful information, thanks. I didn't get to research the differences at all yet as I'm working on all the other parts of a device with LEDs and your driver has been working great so far in ESP IDF `std` environment.

**Comment by cat-in-136** [comment]
I started working on no_std.
For now, the API for allocated memory has not yet been added; meaning alloc is mandatory. That is, there are currently no particular benefits to using no_std.
